export const examsTypes = {
    FETCH_EXAMS : "FETCH_EXAMS",
    FETCH_EXAMS_FAILURE : "FETCH_EXAMS_FAILURE",

    FETCH_EXAM : "FETCH_EXAM",
    FETCH_EXAM_FAILURE : "FETCH_EXAM_FAILURE",

    EDITING_ON: "EDITING_ON",
    EDITING_OFF: "EDITING_OFF",

    ADD_EXAM: "ADD_EXAM",
    ADD_EXAM_FAILURE: "ADD_EXAM_FAILURE",

    DELETE_EXAM: "DELETE_EXAM",
    DELETE_EXAM_FAILURE: "DELETE_EXAM_FAILURE",

    EDIT_EXAM: "EDIT_EXAM",
    EDIT_EXAM_FAILURE: "EDIT_EXAM_FAILURE",
};
