export const userTypes = {
    // Register ~= add user
    REGISTER:  "REGISTER",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    LOGIN: "LOGIN",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT: "LOGOUT",

    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    FETCH_USER: "FETCH_USER",
    FETCH_USER_FAILURE: "FETCH_USER_FAILURE",

    DELETE_USER: "DELETE_USER",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

    UPDATE_USERS: "UPDATE_USERS",
    UPDATE_USERS_FAILURE: "UPDATE_USERS_FAILURE",

    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    FILTER_USERS: "FILTER_USERS",

    EDITING_ON: "EDITING_ON",
    EDITING_OFF: "EDITING_OFF",
};
