export const userTypes = {
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT: "LOGOUT",

    FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

    DELETE_USERS_REQUEST: "DELETE_USERS_REQUEST",
    DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
    DELETE_USERS_FAILURE: "DELETE_USERS_FAILURE",

    UPDATE_USERS_REQUEST: "UPDATE_USERS_REQUEST",
    UPDATE_USERS_SUCCESS: "UPDATE_USERS_SUCCESS",
    UPDATE_USERS_FAILURE: "UPDATE_USERS_FAILURE",

};
